
gen_cm:
  userName: kannan
  password: divya123
  host: rabbitmq-2
  port: 5672
  virtualHost: /
  exchangeName: firms.change-manager.tx
  routingKey: firms.gen-result.*

approver_cm:
  userName: kannan
  password: divya123
  host: rabbitmq-2
  port: 5672
  virtualHost: /
  exchangeName: firms.change-manager.tx
  routingKey: firms.preapproved.*

applier_cm:
  userName: kannan
  password: divya123
  host: rabbitmq-2
  port: 5672
  virtualHost: /
  exchangeName: firms.change-manager.tx
  routingKey: firms.apply.result

change_record_creator:
  userName: kannan
  password: divya123
  host: rabbitmq-2
  port: 5672
  virtualHost: /
  exchangeName: firms.change_record_creator.tx
  routingKey: firms.change.details

  

validator:
  userName: kannan
  password: divya123
  host: rabbitmq-1
  port: 5672
  virtualHost: /
  exchangeName: aggregator
  routingKey: valid
